name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: |
        echo "Running ESLint..."
        npm run lint || EXIT_CODE=$?
        if [ "${EXIT_CODE:-0}" -ne 0 ]; then
          echo "::error::ESLint found errors that must be fixed"
          exit 1
        fi
        echo "✅ ESLint passed (warnings are allowed)"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      shell: bash
      run: |
        if [ -f "package.json" ] && grep -q "\"test\":" package.json; then
          npm test
        else
          echo "No tests configured yet"
        fi

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
      
    - name: Run npm audit fix (dry run)
      run: npm audit fix --dry-run

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for console.log statements
      shell: bash
      run: |
        echo "Checking for console.log statements in production code..."
        if grep -r "console\.log" src/ --exclude-dir=node_modules --exclude="*.test.js" --exclude="*.spec.js"; then
          echo "Warning: console.log statements found in source code"
        fi
        
    - name: Check for TODO comments
      shell: bash
      run: |
        echo "Checking for TODO comments..."
        grep -r "TODO\|FIXME\|HACK" src/ --exclude-dir=node_modules || echo "No TODO comments found"